name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1,3,5"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server

    strategy:
      matrix:
        node: [12, 14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cp .env.example .env
      # we want to test a 'fresh' install for new users
      - run: rm -rf node_modules && rm package-lock.json
      - run: npm install
      # The apps/sources/etc in this project won't validate
      - run: rm -rf config
      - run: npm run import
      - run: mkdir config
      - run: cp __tests__/fixtures/sqlite-source-config.js ./config
      - run: npm run test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
          REDIS_URL: redis://localhost:${{ job.services.redis.ports[6379] }}/0
          PORT: 3000
          WEB_URL: http://localhost:3000
          WEB_SERVER: true
          WORKERS: 1
          GROUPAROO_TELEMETRY_ENABLED: false
